baseURL = 'https://www.weefreemedic.org/'
languageCode = 'en-us'
title = 'Wee Free Medic'
theme = "weefree"
[markup]
  [markup.goldmark.renderer]
    unsafe= true
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
