baseURL = 'https://www.weefreemedicine.org/'
languageCode = 'en-us'
title = 'Wee Free Medicine'
subtitle = 'Whole-Person Medicine, Advanced Skincare, and Medical Teaching for All'
theme = "weefree"
[params]
  phpConfig = "/srv/data/weefree/weefreemail.ini"
  author = 'Mike Dacre'
  description = "Whole-Person Medicine, Advanced Skincare,  and Medical Teaching for All."
[mediaTypes]
  [mediaTypes."application/x-php"]
  suffixes = ["php"]
[outputFormats]
  [outputFormats.PHP]
    mediaType = "application/x-php"
    isPlainText = true
    baseName = "index"
[markup]
  [markup.goldmark.renderer]
    unsafe = true
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
