baseURL = 'https://www.weefreemedic.org/'
languageCode = 'en-us'
title = 'Wee Free Medic'
theme = "weefree"
[params]
  phpConfig = "/srv/data/weefree/weefreemail.ini"
  author = 'Mike Dacre'
  description = "Wee Free Medic provides CPR, First Aid, and Wilderness Medical Training as well as Street Medical and Volunteer EMT services."
[mediaTypes]
  [mediaTypes."application/x-php"]
  suffixes = ["php"]
[outputFormats]
  [outputFormats.PHP]
    mediaType = "application/x-php"
    isPlainText = true
    baseName = "index"
[markup]
  [markup.goldmark.renderer]
    unsafe= true
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
